const localDate=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)},today=()=>localDate(new Date());
const defaults={reservations:[{id:1,date:today(),time:'10:00',name:'김하늘',phone:'010-2384-1902',service:'여성 커트',designer:'서윤 원장',status:'확정',coinUsed:0,price:35000},{id:2,date:today(),time:'11:30',name:'이지민',phone:'010-9921-4420',service:'프리미엄 염색',designer:'하린 디자이너',status:'확정',coinUsed:8000,price:120000},{id:3,date:today(),time:'14:30',name:'박서준',phone:'010-7752-6190',service:'남성 커트',designer:'도윤 디자이너',status:'대기',coinUsed:0,price:25000},{id:4,date:today(),time:'17:30',name:'최유나',phone:'010-4510-2341',service:'디자인 펌',designer:'서윤 원장',status:'확정',coinUsed:0,price:150000}],customers:[{name:'김하늘',phone:'010-2384-1902',last:today(),visits:8,coins:12500},{name:'이지민',phone:'010-9921-4420',last:today(),visits:4,coins:8000},{name:'박서준',phone:'010-7752-6190',last:today(),visits:11,coins:20500},{name:'최유나',phone:'010-4510-2341',last:today(),visits:3,coins:11000}],reviews:[{id:1,name:'김하늘',rating:5,service:'여성 커트',text:'원하는 느낌을 정확히 알아봐 주셔서 편하게 맡겼어요. 손질 방법까지 자세히 알려주셔서 매일 아침이 쉬워졌습니다.',date:'2026.09.15',visible:true},{id:2,name:'이지민',rating:5,service:'프리미엄 염색',text:'공간이 조용하고 상담도 꼼꼼해요. 피부톤에 잘 맞는 색을 추천받았는데 정말 만족합니다.',date:'2026.09.10',visible:true},{id:3,name:'최유나',rating:5,service:'디자인 펌',text:'과하지 않으면서도 분위기가 달라졌어요. 예약제로 운영돼 기다림 없이 여유롭게 받을 수 있어 좋았습니다.',date:'2026.09.03',visible:true}],coinHistory:[{name:'김하늘',amount:2500,type:'add',date:'2026.09.15 · 시술 적립',balance:12500},{name:'박서준',amount:5000,type:'use',date:'2026.09.12 · 코인 사용',balance:20500},{name:'이지민',amount:8000,type:'add',date:'2026.09.10 · 신규 적립',balance:8000}]};
let data=JSON.parse(localStorage.getItem('yeobaekData')||'null')||defaults;data.coinHistory||=[];data.reservations.forEach(r=>{r.coinUsed??=0;r.price??=0});
const save=()=>localStorage.setItem('yeobaekData',JSON.stringify(data)),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],won=n=>Number(n||0).toLocaleString('ko-KR'),phone=v=>String(v||'').replace(/\D/g,''),esc=(v='')=>String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}
function go(id){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0);if(id==='booking'){renderCalendar();renderSlots()}if(id==='admin')renderAll()}$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function adminGo(id){$$('.admin-view').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('[data-admin]').forEach(x=>x.classList.toggle('active',x.dataset.admin===id));$('#adminTitle').textContent={dashboard:'대시보드',reservations:'예약 관리',customers:'고객 관리',coins:'코인 관리',reviewAdmin:'후기 관리'}[id];renderAll()}$$('[data-admin]').forEach(b=>b.onclick=()=>adminGo(b.dataset.admin));
const slots=[];for(let h=10;h<20;h++)for(const m of[0,30])slots.push(`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`);
let selectedDate=today(),selectedTime='',calendarCursor=new Date();calendarCursor.setDate(1);
const prettyDate=v=>new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short'}).format(new Date(v+'T12:00:00'));
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();$('#calendarTitle').textContent=`${y}년 ${m+1}월`;let html='<span class="calendar-empty"></span>'.repeat(first);for(let d=1;d<=days;d++){const value=localDate(new Date(y,m,d)),past=value<today();html+=`<button type="button" class="calendar-day ${value===selectedDate?'selected':''} ${value===today()?'today':''}" data-date="${value}" ${past?'disabled':''}>${d}</button>`}$('#calendarGrid').innerHTML=html;$$('#calendarGrid [data-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;selectedTime='';$('[name=date]').value=selectedDate;$('[name=time]').value='';renderCalendar();renderSlots()});$('#prevMonth').disabled=new Date(y,m,1)<=new Date(new Date().getFullYear(),new Date().getMonth(),1)}
function renderSlots(){$('#slotDateLabel').textContent=prettyDate(selectedDate)+' 예약 현황';const booked=new Set(data.reservations.filter(r=>r.date===selectedDate).map(r=>r.time));$('#timeSlots').innerHTML=slots.map(t=>`<button type="button" class="time-slot ${selectedTime===t?'selected':''}" data-time="${t}" ${booked.has(t)?'disabled title="예약 완료"':''}>${t}</button>`).join('');$$('#timeSlots [data-time]:not(:disabled)').forEach(b=>b.onclick=()=>{selectedTime=b.dataset.time;$('[name=date]').value=selectedDate;$('[name=time]').value=selectedTime;renderSlots()})}
$('#prevMonth').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()};$('[name=date]').value=selectedDate;renderCalendar();renderSlots();
const bookingCustomer=()=>data.customers.find(c=>phone(c.phone)===phone($('[name=phone]').value)),selectedPrice=()=>Number($('#serviceSelect').selectedOptions[0]?.dataset.price||0);
function updateCoinLookup(){const c=bookingCustomer(),e=$('#coinLookup');e.classList.toggle('found',!!c);e.textContent=c?`${c.name} 고객님의 보유 코인: ${won(c.coins)} C`:'등록된 고객 정보가 없습니다. 보유 코인: 0 C';updatePaymentSummary()}
function updatePaymentSummary(){const price=selectedPrice(),c=bookingCustomer(),requested=$('#useCoin').checked?Number($('#bookingCoinAmount').value||0):0,usable=Math.min(requested,c?.coins||0,price);$('#paymentSummary').textContent=price?`시술 금액 ${won(price)}원 · 코인 ${won(usable)} C · 현장 결제 ${won(price-usable)}원`:'시술 메뉴를 선택해주세요.'}
$('[name=phone]').addEventListener('input',updateCoinLookup);$('#serviceSelect').addEventListener('change',updatePaymentSummary);$('#useCoin').onchange=e=>{$('#coinPaymentFields').classList.toggle('active',e.target.checked);updatePaymentSummary()};$('#bookingCoinAmount').addEventListener('input',updatePaymentSummary);$('#useMaxCoin').onclick=()=>{const c=bookingCustomer();if(!c)return toast('등록된 고객의 연락처를 먼저 입력해주세요.');$('#bookingCoinAmount').value=Math.min(c.coins,selectedPrice()||c.coins);updatePaymentSummary()};
$('#bookingForm').onsubmit=e=>{e.preventDefault();if(!selectedDate||!selectedTime)return toast('예약 가능한 날짜와 시간을 먼저 선택해주세요.');if(data.reservations.some(r=>r.date===selectedDate&&r.time===selectedTime)){selectedTime='';renderSlots();return toast('방금 예약된 시간입니다. 다른 시간을 선택해주세요.')}const f=new FormData(e.target),r=Object.fromEntries(f),price=selectedPrice();r.id=Date.now();r.status='대기';r.service=r.service.split(' · ')[0];r.price=price;r.coinUsed=0;let c=data.customers.find(x=>phone(x.phone)===phone(r.phone));if(!c){c={name:r.name,phone:r.phone,last:'첫 방문 예정',visits:0,coins:0};data.customers.unshift(c)}if($('#useCoin').checked){const amount=Number($('#bookingCoinAmount').value||0);if(amount<=0)return toast('사용할 코인 수량을 입력해주세요.');if(amount>c.coins)return toast(`보유 코인은 ${won(c.coins)} C입니다.`);if(amount>price)return toast('시술 금액보다 많은 코인은 사용할 수 없습니다.');r.coinUsed=amount;c.coins-=amount;data.coinHistory.unshift({name:c.name,amount,type:'use',date:`${new Date().toLocaleDateString('ko-KR')} · 예약 결제`,balance:c.coins})}data.reservations.push(r);save();$('#bookingSuccessText').textContent=`${prettyDate(r.date)} ${r.time}\n${r.service} 예약이 접수되었습니다.\n\n사용 코인 ${won(r.coinUsed)} C · 남은 코인 ${won(c.coins)} C\n현장 결제 예정 ${won(price-r.coinUsed)}원`;$('#bookingSuccess').classList.add('open');$('#bookingSuccess').setAttribute('aria-hidden','false');e.target.reset();selectedTime='';$('[name=date]').value=selectedDate;$('[name=time]').value='';$('#coinPaymentFields').classList.remove('active');updateCoinLookup();renderCalendar();renderSlots()};
$('#closeBookingSuccess').onclick=()=>{$('#bookingSuccess').classList.remove('open');$('#bookingSuccess').setAttribute('aria-hidden','true');go('home')};
$('#openReview').onclick=()=>{$('#reviewModal').classList.add('open');$('#reviewModal').setAttribute('aria-hidden','false')};$('#closeReview').onclick=closeReview;$('#reviewModal').onclick=e=>{if(e.target.id==='reviewModal')closeReview()};function closeReview(){$('#reviewModal').classList.remove('open');$('#reviewModal').setAttribute('aria-hidden','true')}
$('#reviewForm').onsubmit=e=>{e.preventDefault();const r=Object.fromEntries(new FormData(e.target));r.id=Date.now();r.rating=+r.rating;r.date=new Date().toLocaleDateString('ko-KR').replace(/\s/g,'');r.visible=true;data.reviews.unshift(r);save();e.target.reset();closeReview();renderReviews();toast('소중한 후기가 등록되었습니다.')};
function renderReviews(){const visible=data.reviews.filter(r=>r.visible);$('#reviewCount').textContent=visible.length;$('#avgRating').textContent=visible.length?(visible.reduce((a,r)=>a+r.rating,0)/visible.length).toFixed(1):'0.0';$('#reviewList').innerHTML=visible.map(r=>`<article class="review-card"><span class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</span><p>${esc(r.text)}</p><footer><b>${esc(r.name[0]+'**')}</b><span>${esc(r.service)} · ${r.date}</span></footer></article>`).join('')||'<p>아직 작성된 후기가 없습니다.</p>'}
function renderAll(){const ts=data.reservations.filter(r=>r.date===today()).sort((a,b)=>a.time.localeCompare(b.time));$('#statToday').textContent=ts.length;$('#statCustomers').textContent=data.customers.length;$('#statCoins').textContent=won(data.customers.reduce((a,c)=>a+c.coins,0));$('#statReviews').textContent=data.reviews.length;$('#todayReservations').innerHTML=ts.map(r=>`<div class="appointment"><time>${r.time}</time><p><b>${esc(r.name)}</b><br><small>${esc(r.service)} · ${esc(r.designer)}</small></p><span class="badge">${r.status}</span></div>`).join('')||'<p class="muted">오늘 예약이 없습니다.</p>';$('#recentCustomers').innerHTML=data.customers.slice(0,4).map(c=>`<div class="customer-mini"><span class="avatar">${esc(c.name[0])}</span><p><b>${esc(c.name)}</b><br><small>${c.visits}회 방문</small></p><strong>${won(c.coins)} C</strong></div>`).join('');$('#reservationTable').innerHTML=data.reservations.slice().sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)).map(r=>`<tr><td>${r.date} ${r.time}</td><td><b>${esc(r.name)}</b><br><small>${esc(r.phone)}</small></td><td>${esc(r.service)}<br><small>코인 ${won(r.coinUsed)} C 사용</small></td><td>${esc(r.designer)}</td><td><span class="badge">${r.status}</span></td><td><button class="action-btn" onclick="removeReservation(${r.id})">삭제</button></td></tr>`).join('');renderCustomers();const selected=$('#coinCustomer').value;$('#coinCustomer').innerHTML=data.customers.map((c,i)=>`<option value="${i}">${esc(c.name)} · ${won(c.coins)} C</option>`).join('');if(selected&&data.customers[+selected])$('#coinCustomer').value=selected;renderSelectedCoin();$('#coinBalances').innerHTML=data.customers.map(c=>`<div class="coin-balance-row"><span class="avatar">${esc(c.name[0])}</span><p><b>${esc(c.name)}</b><br><small>${esc(c.phone)}</small></p><strong>${won(c.coins)} C</strong></div>`).join('');$('#coinHistory').innerHTML=data.coinHistory.map(h=>`<div class="history-item"><span>◇</span><p><b>${esc(h.name)}</b><br><small>${h.date}${h.balance!==undefined?` · 잔액 ${won(h.balance)} C`:''}</small></p><strong class="${h.type==='add'?'plus':h.type==='use'?'minus':''}">${h.type==='add'?'+':h.type==='use'?'−':'='}${won(h.amount)} C</strong></div>`).join('');$('#reviewAdminList').innerHTML=data.reviews.map(r=>`<div class="admin-review"><span class="stars">${'★'.repeat(r.rating)}</span><div class="review-body"><b>${esc(r.name)} · ${esc(r.service)}</b><p>${esc(r.text)}</p><small>${r.date} · ${r.visible?'게시 중':'숨김'}</small></div><button onclick="toggleReview(${r.id})">${r.visible?'숨기기':'게시'}</button><button onclick="removeReview(${r.id})">삭제</button></div>`).join('');renderReviews()}
function renderCustomers(filter=''){const q=filter.toLowerCase();$('#customerTable').innerHTML=data.customers.filter(c=>(c.name+c.phone).toLowerCase().includes(q)).map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone)}</td><td>${c.last}</td><td>${c.visits}회</td><td><b>${won(c.coins)} C</b></td></tr>`).join('')}$('#customerSearch').oninput=e=>renderCustomers(e.target.value);
window.removeReservation=id=>{if(confirm('이 예약을 삭제할까요?')){data.reservations=data.reservations.filter(r=>r.id!==id);save();renderAll();renderSlots();toast('예약이 삭제되었습니다.')}};window.toggleReview=id=>{const r=data.reviews.find(x=>x.id===id);r.visible=!r.visible;save();renderAll();toast(r.visible?'후기를 게시했습니다.':'후기를 숨겼습니다.')};window.removeReview=id=>{if(confirm('이 후기를 삭제할까요?')){data.reviews=data.reviews.filter(r=>r.id!==id);save();renderAll();toast('후기가 삭제되었습니다.')}};
function renderSelectedCoin(){const c=data.customers[+$('#coinCustomer').value];$('#selectedCoinBalance').textContent=c?`${won(c.coins)} C`:'0 C'}$('#coinCustomer').onchange=renderSelectedCoin;
$('#coinForm').onsubmit=e=>{e.preventDefault();const type=e.submitter.value,c=data.customers[+$('#coinCustomer').value],amount=Number($('#coinAmount').value);if(!c||amount<0)return;if(type==='use'&&amount>c.coins)return toast(`보유 코인은 ${won(c.coins)} C입니다.`);if(type==='add')c.coins+=amount;else if(type==='use')c.coins-=amount;else c.coins=amount;data.coinHistory.unshift({name:c.name,amount,type,date:`${new Date().toLocaleDateString('ko-KR')} · 관리자 ${type==='add'?'지급':type==='use'?'사용':'잔액 조정'}`,balance:c.coins});save();$('#coinAmount').value='';renderAll();$('#adminCoinResult').textContent=`${c.name} 고객님의 남은 코인은 ${won(c.coins)} C입니다.`;toast(`처리 완료 · 남은 코인 ${won(c.coins)} C`)};
$('#adminDate').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date());renderReviews();renderAll();
